name = "EmbeddedGraphs"
uuid = "9c1af47c-29f5-11e9-0b47-9f5334384f20"
authors = ["Frank Hellmann <hellmann@pik-potsdam.de>"]
version = "0.1.0"


[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
GraphPlot = "0.4"
julia = "1.0"
